#!/bin/bash

set -euo pipefail

WORKER_HOME=${WORKER_HOME:-/home/vscode}
WORKER_USER=${WORKER_USER:-vscode}
ENV_FILE=${ENV_FILE:-$WORKER_HOME/data/.env}

# Root-only setup: create directories, install xstartup, set ownership, link /workspaces.
if [ "$(id -u)" = '0' ]; then
    echo "Running as root, preparing $WORKER_HOME..."
    mkdir -p "$WORKER_HOME/.vnc" "$WORKER_HOME/.xauth" "$WORKER_HOME/data"
    cp "$WORKER_HOME/xstartup" "$WORKER_HOME/.vnc/xstartup"
    chmod +x "$WORKER_HOME/.vnc/xstartup"
    chown -R "$WORKER_USER:$WORKER_USER" "$WORKER_HOME"
    # /workspaces must be updated as root since it lives at the filesystem root.
    ln -sfn "$WORKER_HOME/data" /workspaces
fi

# Load credentials and environment from the persistent data volume env file.
if [ -f "$ENV_FILE" ]; then
    echo "Loading env from $ENV_FILE"
    set -a
    # shellcheck source=/dev/null
    . "$ENV_FILE"
    set +a
    # Write exports to /etc/profile.d/ so they propagate to all sub-sessions:
    # VNC xstartup, sudo, login shells, and desktop apps.
    grep -v '^\s*#' "$ENV_FILE" | grep -v '^\s*$' | \
        sed 's/^/export /' > /etc/profile.d/worker-env.sh || true
fi

# Start dbus + tigervncserver + noVNC in supervised background restart loops.
# NOTE: desktop-init.sh was generated by install.sh using an unquoted heredoc, so its
# $1/$@ args were baked as empty strings at build time. It always exits after starting
# background services ("No command provided to execute"). We call it as a subprocess
# (not exec) so our entrypoint remains PID 1.
/usr/local/share/desktop-init.sh || true

# If CMD args were passed, launch them in the X session as a background task.
if [ "$#" -gt 0 ]; then
    DISPLAY=:1 "$@" &
fi

# Keep the container alive while the background desktop services run.
exec tail -f /tmp/container-init.log
